from PAGE_OBJECT.Application_Form import application_pages
from UTILITIES.Logger import LogGenerator
import time


class Test_applications:
    log = LogGenerator.loggen()

    def test_application(self, setup):
        self.driver = setup
        self.ap = application_pages(self.driver)
        self.log.info("NEW inter in home page ")
        self.ap.enter_apply_police_patil()
        self.log.info("ENTER APPLY POLICE PATIL POST")
        time.sleep(2)
        self.ap.enter_upvibhag_dd()
        self.log.info("drop down upvibhag  ")
        time.sleep(1)
        self.ap.enter_dd_talukka_name()
        self.log.info("drop down talluka ")
        time.sleep(1)
        self.ap.enter_dd_gaon_name()
        self.log.info("drop down gaon name ")
        time.sleep(1)
        self.ap.enter_dd_rahivasi_yes_no()
        self.log.info("drop down Do you have residence  of this village ")
        time.sleep(1)
        self.ap.enter_photo_upload("D:\\NASHIK_POLICE_PATIL_001\\UPLOAD_IMAGES\\PHOTO.jpg")
        self.log.info("upload candidate photo ")
        time.sleep(1)
        self.ap.enter_full_name("Ram Radheshyam Pande")
        self.log.info("enter candidate full name ")
        self.ap.enter_add("Panchashil Nagar Pulgaon Road Nashik")
        self.log.info("entered candidate full address ")
        self.ap.enter_mobile_no("9673050564")
        self.log.info("entered candidate mobile number ")
        self.ap.enter_email_id("rampande123@gmail.com")
        self.log.info("entered mail id ")
        self.ap.enter_DD_dob("17/12/1984")
        self.log.info("entered DOB of candidate ")
        self.driver.save_screenshot("D:\\NASHIK_POLICE_PATIL_001\\ScreenShots\\candidate_details.jpg")
        self.log.info("TAKE A SCREEN SHOTS OF CANDIDATE DETAILS")
        self.ap.enter_gender()
        self.log.info("selected gender ")
        time.sleep(1)
        self.ap.enter_marital_status()
        self.log.info("selected marital status ")
        time.sleep(1)
        self.ap.enter_no_chield("1")
        self.log.info("entered number of chield ")
        self.ap.enter_cast()
        self.log.info("entered cast ")

        self.ap.enter_ten_school_name("Lokanayak Bapuji Ane Vidhylaya Nashik")
        self.ap.enter_ten_passing_year("2009")
        self.ap.enter_ten_mark_obtain("595")
        self.ap.enter_ten_total_mark("650")
        self.ap.enter_ten_percentage("91.53")
        self.log.info("entered all of information of class 10 ")

        self.ap.enter_12_school_name("Bal gopal High school Nashik")
        self.ap.enter_12_passing_year("2011")
        self.ap.enter_12_mark_obtain("550")
        self.ap.enter_12_total_mark("600")
        self.ap.enter_12_percentage("91.66")
        self.log.info("entered all the information's of class 12 ")

        self.ap.enter_graduation_school_name("Jagdambha Collage Of  Commerce And Science Nashik")
        self.ap.enter_graduation_passing_year("2015")
        self.ap.enter_graduation_mark_obtain("605")
        self.ap.enter_graduation_total_mark("750")
        self.ap.enter_graduation_percentage("80.26")
        self.log.info("entered all the information of Graduation ")
        self.driver.save_screenshot("D:\\NASHIK_POLICE_PATIL_001\\ScreenShots\\candidate_school_details.jpg")
        self.log.info("TAKE A SCREEN SHOTS OF CANDIDATE QUALIFICATIONS")
        time.sleep(1)
        self.ap.enter_have_cast_certificate()
        self.log.info("entered drop down cast  certificate yes or no ")
        time.sleep(1)
        self.ap.enter_cast_certificate_number("AS25012")
        self.log.info("entered cast certificate number ")
        self.ap.enter_cast_certificate_date("16/10/2025")
        self.log.info("entered cast certificate date ")
        self.ap.enter_handicap_yes_no()
        self.log.info("handle fitness certificate  ")
        time.sleep(1)
        self.ap.enter_non_creamy_layer_yes_no()
        self.log.info("handle non creamy layer drop down ")
        time.sleep(1)

        self.ap.upload_cast_certificate("D:\\NASHIK_POLICE_PATIL_001\\UPLOAD_IMAGES\\download (1).pdf")
        self.log.info("upload cast certificate pdf file with given formate ")
        time.sleep(1)
        self.ap.upload_non_creamy_layer("D:\\NASHIK_POLICE_PATIL\\UPLOAD_IMAGES\\download (2).pdf")
        self.log.info("upload non creamy layer certificate PDF File ")
        time.sleep(1)
        self.ap.upload_medical_fitness("D:\\NASHIK_POLICE_PATIL\\UPLOAD_IMAGES\\download (4).pdf")
        self.log.info("upload fitness certificate  ")
        time.sleep(1)
        self.ap.upload_ten_certificate("D:\\NASHIK_POLICE_PATIL\\UPLOAD_IMAGES\\10MAERKSHEET.jpg")
        self.log.info("pload 10 th certificate  ")
        time.sleep(1)
        self.ap.upload_rahivasi("D:\\NASHIK_POLICE_PATIL\\UPLOAD_IMAGES\\download (3).pdf")
        self.log.info("upload residential certificate  ")
        time.sleep(1)
        self.ap.enter_declaration()
        self.log.info("click a declarations")

        self.ap.enter_sing_file("D:\\NASHIK_POLICE_PATIL\\UPLOAD_IMAGES\\SIGN.png")
        self.log.info("upload sing JPG file ")
        time.sleep(1)
        self.ap.enter_pay_and_submit_button()
        self.log.info("clicked pay and submit button ")
        time.sleep(2)
        self.ap.enter_final_submit_pop()
        self.log.info("clicked pop up submit button ")
        time.sleep(5)

        self.ap.enter_card_detail_brand()
        self.log.info("select cards Brand")
        self.ap.enter_card_no("5241")
        self.ap.enter_card_no("6701")
        self.ap.enter_card_no("2345")
        self.ap.enter_card_no("6789")
        self.log.info("card number entered")
        time.sleep(1)
        self.ap.enter_card_holder_name("Nagesh Khade")
        self.log.info("card holder name entered  ")
        self.ap.enter_valid_upto("11/25")
        self.log.info("entered valid upto ")
        self.ap.enter_cvv("289")
        self.log.info("entered CVV ")
        self.driver.save_screenshot("D:\\NASHIK_POLICE_PATIL_001\\ScreenShots\\candidate_bank_details.jpg")
        self.log.info("take a screen shots of  cards details ")
        time.sleep(1)
        self.ap.enter_proceed_to_payment_button()
        self.log.info("clicked proceed button ")
        time.sleep(7)










